# Configuration for job sources
# Add new companies here to scrape their job boards

greenhouse_companies:
  - slug: "airbnb"
    name: "Airbnb"
  - slug: "stripe"
    name: "Stripe"
  - slug: "spotify"
    name: "Spotify"
  - slug: "doordash"
    name: "DoorDash"

lever_companies:
  - slug: "netflix"
    name: "Netflix"
  - slug: "uber"
    name: "Uber"
  - slug: "lyft"
    name: "Lyft"

generic_feeds:
  - url: "https://jobs.github.com/positions.json?search=remote"
    name: "GitHub Jobs"
    type: "json"
  - url: "https://remoteok.io/api"
    name: "Remote OK"
    type: "json"

# Rate limiting configuration
rate_limits:
  default_delay: 1.0  # seconds between requests
  max_retries: 3
  timeout: 30