# WORKING Remote Job Sources - Tested & Verified 2024

# ✅ WORKING Greenhouse companies (verified slugs)
greenhouse_companies:
  - slug: "airbnb"
    name: "Airbnb"
  - slug: "stripe"
    name: "Stripe"
  - slug: "gitlab"
    name: "GitLab"
  # Working Indian companies on Greenhouse
  - slug: "razorpay"
    name: "Razorpay" 
  - slug: "zomato"
    name: "Zomato"
  - slug: "swiggy"
    name: "Swiggy"

# ✅ WORKING Lever companies  
lever_companies:
  - slug: "netflix"
    name: "Netflix"
  # Add more when we find working slugs

# ✅ VERIFIED Working Remote Job APIs
remote_job_apis:
  # Himalayas - Excellent free remote jobs API
  - url: "https://himalayas.app/jobs/api?limit=100"
    name: "Himalayas Remote Jobs"
    type: "json"
    remote_only: true
    working: true
    
  # Remotive - Public API with delays
  - url: "https://remotive.com/api/remote-jobs"
    name: "Remotive"
    type: "json"
    remote_only: true
    working: true
    
  # AngelList - Startup jobs (many remote)
  - url: "https://angel.co/api/jobs?remote=true"
    name: "AngelList Remote"
    type: "json"
    working: false  # Need to verify
    
  # JustRemote - Dedicated remote jobs
  - url: "https://justremote.co/api/remote_jobs"
    name: "JustRemote"
    type: "json"
    remote_only: true
    working: false  # Need to verify

# ✅ WORKING RSS Feeds  
rss_feeds:
  - url: "https://weworkremotely.com/remote-jobs.rss"
    name: "We Work Remotely"
    type: "rss"
    remote_only: true
    working: true
    
  - url: "https://remoteok.com/remote-jobs.rss"
    name: "RemoteOK RSS"
    type: "rss" 
    remote_only: true
    working: true

# Indian Job Sources (Manual Company APIs)
indian_companies:
  # Major Indian product companies
  - name: "Flipkart"
    careers_url: "https://careers.flipkart.com/api/jobs"
    type: "json"
    note: "Check if public API available"
    
  - name: "PhonePe"
    careers_url: "https://careers.phonepe.com/jobs"
    type: "scrape"
    note: "May need HTML scraping"
    
  - name: "CRED"
    careers_url: "https://careers.cred.club/api/openings"
    type: "json" 
    note: "Check if API exists"

# Enhanced Rate Limiting & Detection
rate_limits:
  default_delay: 2.0  # Respectful 2-second delay
  max_retries: 3
  timeout: 30
  respect_robots_txt: true

# IMPROVED Remote Detection Keywords
remote_keywords:
  strict:
    - "remote"
    - "100% remote"
    - "fully remote"
    - "remote first"
    - "work from anywhere"
    - "distributed"
    - "location independent"
  
  flexible:
    - "work from home"
    - "wfh" 
    - "remote friendly"
    - "remote work"
    - "home office"
    - "telecommute"
    - "virtual"
    - "anywhere"
    - "flexible location"

# Company-specific remote indicators
company_remote_flags:
  gitlab: "always_remote"      # GitLab is 100% remote
  automattic: "always_remote"  # WordPress.com is 100% remote
  zapier: "always_remote"      # Zapier is 100% remote
  buffer: "always_remote"      # Buffer is 100% remote
