# ENHANCED ATS Platform Support + RSS Feeds

# ✅ Greenhouse Companies (Working)
greenhouse_companies:
  - slug: "airbnb"
    name: "Airbnb"
  - slug: "stripe"
    name: "Stripe"
  - slug: "gitlab"
    name: "GitLab"

# 🔧 LEVER COMPANIES (Enhanced with known working slugs)
lever_companies:
  - slug: "netflix"
    name: "Netflix"
  - slug: "uber"
    name: "Uber"
  - slug: "spotify"
    name: "Spotify"
  - slug: "shopify"
    name: "Shopify"
  - slug: "atlassian"
    name: "Atlassian"
  - slug: "canva"
    name: "Canva"
  - slug: "notion"
    name: "Notion"
  - slug: "figma"
    name: "Figma"
  # Indian companies on Lever
  - slug: "meesho"
    name: "Meesho"
  - slug: "swiggy"
    name: "Swiggy"

# 🏢 WORKDAY COMPANIES (RSS feeds)
workday_companies:
  # Major tech companies using Workday
  - slug: "apple"
    name: "Apple"
    rss_url: "https://jobs.apple.com/rss"
    
  - slug: "microsoft"
    name: "Microsoft"
    rss_url: "https://careers.microsoft.com/rss"
    
  - slug: "salesforce"
    name: "Salesforce"
    rss_url: "https://salesforce.wd1.myworkdayjobs.com/External_Career_Site/rss"
    
  - slug: "adobe"
    name: "Adobe"
    rss_url: "https://adobe.wd5.myworkdayjobs.com/external_experienced/rss"
    
  - slug: "servicenow"
    name: "ServiceNow"
    rss_url: "https://servicenow.wd5.myworkdayjobs.com/servicenow_careers/rss"
    
  # Indian companies on Workday
  - slug: "tcs"
    name: "TCS"
    rss_url: "https://tcs.wd3.myworkdayjobs.com/TCS_Careers/rss"

# 💼 SMARTRECRUITERS COMPANIES
smartrecruiters_companies:
  - slug: "zomato"
    name: "Zomato"
    api_url: "https://careers.smartrecruiters.com/Zomato1"
    
  - slug: "booking"
    name: "Booking.com"
    api_url: "https://careers.smartrecruiters.com/BookingHoldings"
    
  - slug: "deliveryhero"
    name: "Delivery Hero"
    api_url: "https://careers.smartrecruiters.com/DeliveryHero"

# 📡 RSS JOB FEEDS (ChatGPT's suggestion - very effective!)
rss_job_feeds:
  # Major job boards with RSS
  - url: "https://weworkremotely.com/remote-jobs.rss"
    name: "We Work Remotely"
    type: "rss"
    remote_only: true
    working: true
    
  - url: "https://stackoverflow.com/jobs/feed?r=true&q=remote"
    name: "Stack Overflow Remote"
    type: "rss"
    focus: "Programming, Development"
    working: true
    
  - url: "https://www.dice.com/jobs/rss?q=remote&l="
    name: "Dice Remote Tech Jobs"
    type: "rss"
    focus: "Enterprise IT, DevOps"
    working: true
    
  - url: "https://rss.indeed.com/rss?q=remote+developer&l="
    name: "Indeed Remote Developers"
    type: "rss"
    focus: "All development roles"
    working: true
    
  # Specialized RSS feeds
  - url: "https://remoteok.io/remote-jobs.rss"
    name: "RemoteOK RSS"
    type: "rss"
    remote_only: true
    working: true
    
  - url: "https://angel.co/jobs/rss?remote=true"
    name: "AngelList Remote RSS"
    type: "rss"
    focus: "Startups, equity"
    working: true
    
  # Tech-specific RSS feeds
  - url: "https://jobs.github.com/positions.rss?description=remote"
    name: "GitHub Jobs RSS"
    type: "rss"
    focus: "Open source, DevOps"
    working: false  # Service discontinued
    
  # Company-specific RSS feeds
  - url: "https://careers.google.com/api/v3/search/?location=Remote"
    name: "Google Remote Jobs RSS"
    type: "json"
    working: false  # Need to verify API

# 🌍 JSON APIs (Reliable sources)
json_api_sources:
  - url: "https://www.workingnomads.co/api/exposed_jobs"
    name: "Working Nomads"
    type: "json"
    remote_only: true
    working: true
    
  - url: "https://himalayas.app/jobs/api?limit=100&remote=true"
    name: "Himalayas"
    type: "json"
    remote_only: true
    working: true
    
  - url: "https://remotive.io/api/remote-jobs"
    name: "Remotive"
    type: "json"
    remote_only: true
    working: true
    
  # Indian job portals with APIs
  - url: "https://www.naukri.com/jobapi/v4/search?remote=1"
    name: "Naukri Remote API"
    type: "json"
    focus: "Indian market"
    working: false  # Need verification
    
  - url: "https://hirect.in/api/jobs?remote=true"
    name: "Hirect Remote API"
    type: "json"
    focus: "Indian startups"
    working: false

# 🔍 COMPANY-SPECIFIC RSS FEEDS (Major tech companies)
company_rss_feeds:
  # FAANG companies
  - url: "https://careers.google.com/api/v3/search/?q=remote"
    name: "Google Careers"
    type: "json"
    company: "Google"
    
  - url: "https://www.amazon.jobs/en/search.rss?base_query=&loc_query=Remote"
    name: "Amazon Remote Jobs"
    type: "rss"
    company: "Amazon"
    
  - url: "https://www.facebook.com/careers/v2/jobs/rss/?q=remote"
    name: "Meta Remote Jobs"
    type: "rss"
    company: "Meta"
    
  # Indian unicorns
  - url: "https://careers.flipkart.com/api/jobs"
    name: "Flipkart Jobs API"
    type: "json"
    company: "Flipkart"
    working: false

# Enhanced Configuration
rate_limits:
  default_delay: 2.5  # Slightly slower for ATS platforms
  max_retries: 3
  timeout: 45
  respect_robots_txt: true

# ATS-Specific Settings
ats_settings:
  workday:
    user_agent: "Mozilla/5.0 (compatible; JobBot/1.0)"
    delay: 3.0  # Workday is slower
    
  lever:
    delay: 2.0
    
  smartrecruiters:
    delay: 2.0
    api_key_required: false

# Remote Detection Keywords (Enhanced for ATS)
remote_keywords:
  strict:
    - "remote"
    - "100% remote"
    - "fully remote"
    - "work from anywhere"
    - "distributed team"
    - "remote first"
    
  flexible:
    - "work from home"
    - "wfh"
    - "remote friendly"
    - "hybrid remote"
    - "flexible location"
    
  ats_specific:
    - "remote eligible"
    - "remote work available"
    - "location flexible"
    - "virtual position"